### PR TITLE
Added VPN Feature

### PR DESCRIPTION
**Pull request by Rsifff**
Hi, it's me again :wave:
Small feature to play on Hack The Box

### CODE REVIEW

**Comment by ShutdownRepo** [comment]
Hey that's nice! I suppose the VPN feature allows user to run openvpn inside the docker container, but I don't know what the :Z flag is used for when mounting volumes, what is it?
Please keep in mind the PRs will not be accepted on the master branch, please move it to dev

**Comment by Rsifff** [comment]
To allow a docker container to access a volume on a SELinux-compatible host, you must attach the "z" or "Z" flag to the volume mount. 
    The "z" option indicates that the content of the linked mount is shared between multiple containers.
    The "Z" option indicates that the content of the linked mount is private and not shared.

**Comment by ShutdownRepo** [comment]
Okay nice
Will this "z" flag cause issues on non-SELinux hosts?

**Comment by ShutdownRepo** [comment]
I temporarily deleted the `dev` branch, your PR was then closed.
Since I have no update from you I'm keeping it closed for now, don't hesitate to open it again with further information :+1:

**Pull request closed without merging**
